[package]
name = "yv_core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1", features = ["v4", "serde"] }
rayon = { version = "1.11" }
hashbrown = { version = "0.16", features = ["serde"] }
ambassador = "0.4"
rand = "0.9"
